### ISSUE TITLE
Shopping Cart - Delete

### ISSUE THREAD

**Issue by colinlwhite** [partingpets/partingpets_fe#35] opened 2019-06-26 00:26 UTC
## User Story
As a user when I access my shopping cart I should be able to delete specific products from my shopping cart

## Tech Notes
Add `delete` button to the shopping cart page 
Add delete function to `shoppingCartRequests.js` for Axios call to the back end

## Acceptance Criteria
When the user clicks the `Delete` button on a line item within their shopping cart
Then the product should be removed from the shopping cart
And show the remaining items in the shopping cart

**Comment by MCrank** [comment] 2019-07-01 20:39
Closed PR #45  I did not see this in the list of issues so I created a new Shopping Cart Delete which is a duplicate of this one.  Closing this since it was already completed with stated PR

**Closed by MCrank** 2019-07-01 20:39 UTC
Labels: enhancement
